// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/exchange-rate": {
            "get": {
                "description": "fetch KRW and USDT price and get price diff",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "calculate exchange rate premium",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateExchangeRateDiffResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Get server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "Show the health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/api/indicator": {
            "get": {
                "description": "crawl tradingview for dxy and insert to db",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "crawl financial indicators",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ScrapeDollarIndexResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateExchangeRateDiffResponse": {
            "type": "object",
            "properties": {
                "exchange_rate_diff": {
                    "type": "string"
                },
                "strong": {
                    "type": "string"
                }
            }
        },
        "dto.ScrapeDollarIndexResponse": {
            "type": "object",
            "properties": {
                "dollar_index": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SignalDash API",
	Description:      "SignalDash backend API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
